version: "3.8"

services:
  pool-db:
    image: postgres:14-alpine
    container_name: pool-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - poll-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  pool-app:
    build:
      context: .
      dockerfile: _configs/Dockerfile
    container_name: pool-app
    command: bash start.sh
    env_file:
      - .env
    environment:
      WAIT-HOSTS: pool-db
    volumes:
      - ./src:/home/pool_users/app
    ports:
      - "5000:5000"
    tty: true
    restart: on-failure
    depends_on:
      - pool-db
#  poll-ui:
#    build:
#      dockerfile: _configs/DockerfileUI
#      args:
#        - GIT_TOKEN=${GIT_TOKEN}
#    container_name: poll-ui
#    ports:
#      - "80:80"
#      - "443:443"
#    env_file:
#      - .env
#    environment:
#      - VUE_APP_BACKEND_URL=http://poll-app:5000

volumes:
  poll-db-data:

networks:
  pool-network:
    external: false