version: "3.8"

services:
  poll-db:
    image: postgres:14-alpine
    container_name: poll-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - poll-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  poll-mongo:
    image: mongo:4.4
    container_name: poll-mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

  poll-backend:
    build:
      context: .
      dockerfile: _configs/Dockerfile
      target: 'production-stage'
    container_name: poll-backend
    env_file:
      - .env
    environment:
      WAIT-HOSTS: "poll-db"
    volumes:
      - ./src:/home/poll_users/app
    ports:
      - "5000:5000"
    tty: true
    restart: on-failure
    depends_on:
      - poll-db
      - poll-mongo
    user: "${UID}:${GID}"


  poll-frontend:
    build:
      context: ../poll_frontend
      dockerfile: _configs/Dockerfile
      target: 'production-stage'
    container_name: poll-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poll-frontend.rule=Host(`testdesk.ru`)"
      - "traefik.http.routers.poll-frontend.entrypoints=websecure"
      - "traefik.http.routers.poll-frontend.tls.certresolver=lets-encrypt"

    depends_on:
      - poll-backend

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--api.dashboard=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./traefik/certificates:/certificates"
    labels:
      - "traefik.enable=true"

    ports:
      - "6000:80"
      - "443:443"

    depends_on:
      - poll-frontend


volumes:
  poll-db-data:
  mongodb_data:
