"""Rollback all downgrade and set relashionship between user and poll

Revision ID: 0f38b1ba8ef8
Revises: e9cad6d81fcb
Create Date: 2023-08-10 11:35:56.394709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f38b1ba8ef8'
down_revision = 'e9cad6d81fcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE pollstatus AS ENUM ('DRAFT', 'PUBLISHED', 'CLOSED', 'ENDED', 'ARCHIVED')")
    op.add_column('poll', sa.Column('poll_status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'CLOSED', 'ENDED', 'ARCHIVED', name='pollstatus'), nullable=True))
    op.drop_column('poll', 'is_active')
    op.drop_constraint('response_user_id_fkey', 'response', type_='foreignkey')
    op.drop_column('response', 'user_id')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE pollstatus")
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('response', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('response_user_id_fkey', 'response', 'user', ['user_id'], ['id'])
    op.add_column('poll', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('poll', 'poll_status')
    # ### end Alembic commands ###
