"""Add status to invitation model

Revision ID: 1c4249cb2fb2
Revises: c7f777cd4804
Create Date: 2023-12-15 05:47:48.362418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4249cb2fb2'
down_revision = 'c7f777cd4804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'is_active')
    # ### end Alembic commands ###
