"""Change Enum TypeQuestion

Revision ID: 3086f4b2bb11
Revises: ace76bc75a10
Create Date: 2023-12-20 11:57:51.587148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3086f4b2bb11'
down_revision = 'ace76bc75a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создание нового типа Enum с обновленными значениями
    op.execute("CREATE TYPE new_typequestion AS ENUM ('SINGLE ANSWER', 'PLURAL ANSWER', 'PLURAL TEXT', 'SINGLE TEXT')")

    # Изменение типа столбца на новый Enum
    op.execute("ALTER TABLE question ALTER COLUMN type TYPE new_typequestion USING type::text::new_typequestion")

    # Удаление старого Enum
    op.execute("DROP TYPE typequestion")

    # Переименование нового типа в старое название
    op.execute("ALTER TYPE new_typequestion RENAME TO typequestion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создание временного типа Enum с предыдущими значениями
    op.execute(
        "CREATE TYPE old_typequestion AS ENUM ('SINGLE ANSWER', 'PLURAL ANSWER', 'FREE ANSWER', 'FREE TEXT ANSWER')")

    # Изменение типа столбца на старый Enum
    op.execute("ALTER TABLE question ALTER COLUMN type TYPE old_typequestion USING type::text::old_typequestion")

    # Удаление нового Enum
    op.execute("DROP TYPE typequestion")

    # Переименование временного типа в старое название
    op.execute("ALTER TYPE old_typequestion RENAME TO typequestion")
    # ### end Alembic commands ###
