"""Add cascade delete to responses

Revision ID: 3a85b1903858
Revises: bee6f7fba754
Create Date: 2024-04-05 04:54:21.304519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a85b1903858'
down_revision = 'bee6f7fba754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('choice_question_id_fkey', 'choice', type_='foreignkey')
    op.create_foreign_key(None, 'choice', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('response_poll_id_fkey', 'response', type_='foreignkey')
    op.drop_constraint('response_question_id_fkey', 'response', type_='foreignkey')
    op.create_foreign_key(None, 'response', 'poll', ['poll_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'response', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('response_question_id_fkey_cascade', 'response', type_='foreignkey')
    op.drop_constraint('response_poll_id_fkey_cascade', 'response', type_='foreignkey')
    op.create_foreign_key('response_question_id_fkey', 'response', 'question', ['question_id'], ['id'])
    op.create_foreign_key('response_poll_id_fkey', 'response', 'poll', ['poll_id'], ['id'])
    op.drop_constraint('choice_question_id_fkey_cascade', 'choice', type_='foreignkey')
    op.create_foreign_key('choice_question_id_fkey', 'choice', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
