"""Updated Poll User Company with created at

Revision ID: 4c9805025244
Revises: ef2de903ddb7
Create Date: 2024-05-16 05:13:39.581959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c9805025244'
down_revision = 'ef2de903ddb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания'))
    op.alter_column('poll', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата создания',
               existing_nullable=True)
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.alter_column('poll', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата создания',
               existing_nullable=True)
    op.drop_column('company', 'created_at')
    # ### end Alembic commands ###
