"""Remove extra field from User model

Revision ID: 6652bd9a9b05
Revises: 0f38b1ba8ef8
Create Date: 2023-08-10 12:54:41.120765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6652bd9a9b05'
down_revision = '0f38b1ba8ef8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
