"""Add fields to User - company_id, company

Revision ID: 6eb56d5ad8ac
Revises: d57d41a0bb07
Create Date: 2023-09-19 07:41:03.677707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb56d5ad8ac'
down_revision = 'd57d41a0bb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='Наименование'),
    sa.Column('full_name', sa.String(), nullable=True, comment='Полное наименование'),
    sa.Column('inn', sa.String(), nullable=True, comment='ИНН'),
    sa.Column('legal_address', sa.String(), nullable=True, comment='Юридический адрес'),
    sa.Column('actual_address', sa.String(), nullable=True, comment='Фактический адрес'),
    sa.Column('phone', sa.String(), nullable=True, comment='Телефон'),
    sa.Column('director_name', sa.String(), nullable=True, comment='Ф.И.О руководителя'),
    sa.Column('admin_email', sa.String(), nullable=True, comment='Почта для регистрации админа'),
    sa.Column('licenses', sa.Integer(), nullable=True, comment='Количество лицензий'),
    sa.Column('subscription_start', sa.DateTime(), nullable=True, comment='Дата начала подписки'),
    sa.Column('subscription_end', sa.DateTime(), nullable=True, comment='Дата окончания подписки'),
    sa.Column('subscription_active', sa.Boolean(), nullable=True, comment='Статус подписки'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_admin_email'), 'company', ['admin_email'], unique=True)
    op.create_index(op.f('ix_company_full_name'), 'company', ['full_name'], unique=False)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_inn'), 'company', ['inn'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'company_id')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_inn'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_company_full_name'), table_name='company')
    op.drop_index(op.f('ix_company_admin_email'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
