"""Add text_fiels_count in Choice model

Revision ID: 8dc379362167
Revises: 6652bd9a9b05
Create Date: 2023-08-14 08:37:53.308776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc379362167'
down_revision = '6652bd9a9b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choice', sa.Column('text_fields_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choice', 'text_fields_count')
    # ### end Alembic commands ###
