"""Change token field from string to text

Revision ID: ace76bc75a10
Revises: 1c4249cb2fb2
Create Date: 2023-12-15 09:54:56.600398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace76bc75a10'
down_revision = '1c4249cb2fb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
