"""Updated models relashionships

Revision ID: bedcbe544093
Revises: 4c9805025244
Create Date: 2024-05-17 10:16:36.594907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedcbe544093'
down_revision = '4c9805025244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
