"""Remove response relashionship from Choice Model

Revision ID: bee6f7fba754
Revises: dc5028dc9031
Create Date: 2024-02-14 10:56:17.318774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee6f7fba754'
down_revision = 'dc5028dc9031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
