"""Add active_from, active_duration and max_participants in Poll

Revision ID: c695d9b32a77
Revises: ace76bc75a10
Create Date: 2024-01-18 11:38:30.835259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c695d9b32a77'
down_revision = 'ace76bc75a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('active_from', sa.DateTime(), nullable=True))
    op.add_column('poll', sa.Column('active_duration', sa.Integer(), nullable=True))
    op.add_column('poll', sa.Column('max_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'max_participants')
    op.drop_column('poll', 'active_duration')
    op.drop_column('poll', 'active_from')
    # ### end Alembic commands ###
