"""create initial tables

Revision ID: c753652d26b6
Revises: 
Create Date: 2023-05-23 10:32:12.153287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c753652d26b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('poll_cover', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('poll_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_description'), 'poll', ['description'], unique=False)
    op.create_index(op.f('ix_poll_id'), 'poll', ['id'], unique=False)
    op.create_index(op.f('ix_poll_title'), 'poll', ['title'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('SINGLE', 'PLURAL', 'FREE', 'FREE_TEXT', name='typequestion'), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('question_cover', sa.String(), nullable=True),
    sa.Column('option_pass', sa.Boolean(), nullable=True),
    sa.Column('option_other_answer', sa.Boolean(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_index(op.f('ix_question_text'), 'question', ['text'], unique=False)
    op.create_index(op.f('ix_question_type'), 'question', ['type'], unique=True)
    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('choice_cover', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_choice_id'), 'choice', ['id'], unique=False)
    op.create_index(op.f('ix_choice_text'), 'choice', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_choice_text'), table_name='choice')
    op.drop_index(op.f('ix_choice_id'), table_name='choice')
    op.drop_table('choice')
    op.drop_index(op.f('ix_question_type'), table_name='question')
    op.drop_index(op.f('ix_question_text'), table_name='question')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_poll_title'), table_name='poll')
    op.drop_index(op.f('ix_poll_id'), table_name='poll')
    op.drop_index(op.f('ix_poll_description'), table_name='poll')
    op.drop_table('poll')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
