"""Add admin_name to company

Revision ID: c7f777cd4804
Revises: 98202d9510c2
Create Date: 2023-11-22 05:27:25.440723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f777cd4804'
down_revision = '98202d9510c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('admin_name', sa.String(), nullable=True, comment='Ф.И.О админинистратора'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'admin_name')
    # ### end Alembic commands ###
