"""Add Company Table

Revision ID: d57d41a0bb07
Revises: 8dc379362167
Create Date: 2023-09-19 07:30:53.734529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d41a0bb07'
down_revision = '8dc379362167'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
