"""Add UserSession table

Revision ID: d6ab047ecff9
Revises: c695d9b32a77
Create Date: 2024-01-23 12:16:48.067013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ab047ecff9'
down_revision = 'c695d9b32a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_uuid', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_uuid'], ['poll.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_id'), 'usersession', ['id'], unique=False)
    op.create_index(op.f('ix_usersession_token'), 'usersession', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usersession_token'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_id'), table_name='usersession')
    op.drop_table('usersession')
    # ### end Alembic commands ###
