"""Add uuid field to poll model

Revision ID: e9cad6d81fcb
Revises: 3e90301f06e3
Create Date: 2023-08-03 21:06:11.414218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cad6d81fcb'
down_revision = '3e90301f06e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('uuid', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'poll', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='unique')
    op.drop_column('poll', 'uuid')
    # ### end Alembic commands ###
