"""Add user_token field to Response model

Revision ID: ef2de903ddb7
Revises: 3a85b1903858
Create Date: 2024-04-12 04:43:18.039601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2de903ddb7'
down_revision = '3a85b1903858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('user_token', sa.String(), nullable=False))
    op.create_index(op.f('ix_response_user_token'), 'response', ['user_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_user_token'), table_name='response')
    op.drop_column('response', 'user_token')
    # ### end Alembic commands ###
