[entryPoints]
  [entryPoints.web]
    address = ":80"

[accessLog]

[api]
  insecure = true
  dashboard = true



[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false


